learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls', namespace='users')),
    path(r'', include('learning_logs.urls', namespace='learning_log')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.conf.urls import url
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),

    # Show all topics.
    url(r'^topics/$', views.topics, name='topics'),

    # Detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # Page for adding a new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # Page for adding a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    
    # Page for editing an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

]

users/urls.py
"""Defines URL patterns for learning_logs."""
from django.conf.urls import url
from django.contrib.auth.views import LoginView
#from django.contrib.auth import authenticate, login
#from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    # Login page
    #url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # Registration page
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)

    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
        
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            print('=====VALID')
            new_user = form.save()
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            
            login(request, authenticated_user)
            
            return HttpResponseRedirect(reverse('learning_logs:index'))
        else:
            print('===== NOT  VALID')
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{# Load the tag library #}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Learning Log</title>

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</head>
<body>
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<nav class="navbar navbar-dark bg-dark navbar-expand-lg ">
  <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Django Learning Log</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'learning_logs:index' %}">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
    </li>
  </ul>

  {% if user.is_authenticated %}
    <span class="navbar-text">Hello, {{ user.username }}</span>
    <span class="navbar-text"><a class="nav-link" href="{% url 'users:logout' %}">Log out</a></span>
  {% else %}
    <span class="navbar-text"><a class="nav-link" href="{% url 'users:login' %}">Log in</a></span>
    <span class="navbar-text"><a class="nav-link" href="{% url 'users:register' %}">Register</a></span>
  {% endif %}
  </div>
</nav>

<div class="container">
  <div class="page-header">
    {% block header %}{% endblock header %}
  </div>

  <div>
    {% block content %}{% endblock content %}
  </div>
</div>

</body>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block header %}
  <h2>Edit entry</h2>
{% endblock header %}

{% block content %}

<p>
  <a href="{% url 'learning_logs:topic' topic.id %}">&larr; back to topic "{{ topic.text }}"</a>
</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
  {% csrf_token %}
  
  {% bootstrap_form form %}

  {% buttons %}
    <button name="submit" class="btn btn-primary">Save</button>
  {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1 class="display-4">Track your learning.</h1>

    <p class="lead">This project allows you to save your learning progress. 
      You'll never lose your knowledge</p>
    <p>
      <a class="btn btn-primary" href="{% url 'learning_logs:topics' %}">See topics</a>
    </p>
  </div>
{% endblock header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block header %}
  <h2>Add a new entry for topic</h2>
{% endblock header %}

{% block content %}
    <p>
      <a href="{% url 'learning_logs:topic' topic.id %}">&larr; Back to topic "{{ topic.text }}"</a>
    </p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">Save</button>
      {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block header %}
  <h2>Add a new topic</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        
        {% bootstrap_form form %}

        {% buttons %}
          <button name="submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
<h5>This topic's entries</h5>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Text</th>
      <th scope="col">Date added</th>
      <th scope="col">Controls</th>
    </tr>
  </thead>
  <tbody>

  {% for entry in entries %}

    <tr>
      <td>{{ entry.text|linebreaks }}</td>
      <td>{{ entry.date_added|date:'M d, Y H:i' }}</td>
      <td><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit</a></td>
    </tr>

  {% empty %}

    <tr>
      <td colspan="3">There are no entries for this topic yet</td>
    </tr>

  {% endfor %}

  </tbody>
</table>

<a class="btn btn-primary" href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}
<ul>
  {% for topic in topics %}
    <li><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
  {% empty %}
    <li>No topics have been added yet.</li>
  {% endfor %}
</ul>

<a class="btn btn-primary" href="{% url 'learning_logs:new_topic' %}">Add new topic</a>

{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block header %}
  <h2>Log in or <a href="{% url 'users:register' %}">Register</a></h2>
{% endblock header %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block header %}
  <h2>Registration form</h2>
{% endblock header %}

{% block content %}
  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Register</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
{% endblock content %}